name: Go Build

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/go-docker.yaml
  pull_request:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Print the current directories and file within
      - name: Print current directory (for debugging)
        run: |
          pwd
          ls -R
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: user/app:latest
      #     cache-from: type=registry,ref=user/app:buildcache
      #     cache-to: type=registry,ref=user/app:buildcache,mode=max

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
