name: Go Build

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/go-build.yaml
  pull_request:
    branches:
      - main

jobs:
  # First stage: Build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Print the current directories and file within
      - name: Print current directory (for debugging)
        run: |
          pwd
          ls -R

      # Install Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      #----------initial 1st try --->> works OK
      # - name: Build Go Application
      #   run: go build -o app ./main.go

      #----------initial 2st change --->> works OK
      # - name: Build Go Application
      #   run: go build -o ~./main.go

      #----------initial 3rd change --->> works OK
      # also check the files after build
      - name: Build Go Application
        run: |
          go build -o app main.go
          pwd            
          ls -lt
