name: Go-Trivy-check

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/trivy-demo.yaml # worflow only runs if change in the following file
  pull_request:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      #-------------- Code Checkout Stage --------------#
      - name: Checkout code
        uses: actions/checkout@v3

      #-------------- Install Docker Buildx --------------#
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #-------------- Login to dockerhub --------------#
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #-------------- Login to Digital Ocean --------------#
      # - name: Login to DigitalOcean Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: registry.digitalocean.com
      #     username: ${{ vars.DIGITALOCEAN_USERNAME }}
      #     password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      #-------------- Build docker Image --------------#
      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          # context: .
          push: false # Do not push yet, just build the image locally
          load: true # must load image before tag
          tags: akshaydhumale/app
          cache-from: type=local,src=/tmp/.buildx-cache # local
          cache-to: type=local,dest=/tmp/.buildx-cache # local

          # Caching from docker registory
          # cache-from: type=registry,ref= akshaydhumale/app:buildcache
          # cache-to: type=registry,ref= akshaydhumale/app:buildcache,mode=max

      #-------------- List Docker image for debug --------------#
      - name: Cheking docker images
        run: docker images

      #-------------- Trivy scan --------------#

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@0.28.0
      #   with:
      #     image-ref: "akshaydhumale/app"
      #     format: "table"
      #     exit-code: "1"
      #     ignore-unfixed: true
      #     vuln-type: "os,library"
      #     severity: "HIGH,CRITICAL"

      #-------------- Manual Trivy Installation & Scan --------------#
      # - name: Download Trivy
      #   uses: aquasecurity/trivy-action@master

      # - name: Scan Docker image with Trivy
      #   id: trivy-scan
      #   env:
      #     TRIVY_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      #     TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      #   run: |
      #     trivy image --exit-code 1 --severity HIGH,CRITICAL akshaydhumale/app:latest

      #-------------- If Scan Successful Push to DockerHub --------------#
      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v6
        with:
          push: true # Only push if previous steps succeeded
          tags: akshaydhumale/app
