# name: Go-Trivy-check

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - .github/workflows/trivy-demo.yaml
#   pull_request:
#     branches:
#       - main
# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ vars.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build Docker image
#         id: build
#         uses: docker/build-push-action@v6
#         with:
#           push: false # Do not push yet, just build the image locally
#           tags: akshaydhumale/app:latest
#           cache-from: type=local,src=/tmp/.buildx-cache
#           cache-to: type=local,dest=/tmp/.buildx-cache
#           # cache-from: type=registry,ref= akshaydhumale/app:buildcache
#           # cache-to: type=registry,ref= akshaydhumale/app:buildcache,mode=max

#       - name: Download Trivy
#         uses: aquasecurity/trivy-action@master

#       - name: Scan Docker image with Trivy
#         id: trivy-scan
#         env:
#           TRIVY_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
#           TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
#         run: |
#           trivy image --exit-code 1 --severity HIGH,CRITICAL akshaydhumale/app:latest

#       - name: Push Docker image
#         if: success()
#         uses: docker/build-push-action@v6
#         with:
#           push: true # Only push if previous steps succeeded
#           tags: akshaydhumale/app:latest

#---------------- tetsing the trivy action ------------------------
name: Go-Trivy-check

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/trivy-demo.yaml
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build an image from Dockerfile
        run: docker build -t akshaydhumale/app:v1 .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "akshaydhumale/app:v1"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      # Step 7: Install Trivy
      # - name: Install Trivy
      #   uses: aquasecurity/setup-trivy@v0.2.2
      #   with:
      #     version: v0.56.2
      #     cache: true
      # # Step 8: Scan Docker image with Trivy

      # - name: Scan Docker image with Trivy
      #   id: trivy-scan
      #   run: |
      #     trivy image --exit-code 1 --severity HIGH,CRITICAL akshaydhumale/app:v1
